/**
 * Telegram HTML Formatter
 *
 * Converts standard Markdown (as generated by LLMs) into Telegram-compatible HTML.
 * Telegram's HTML mode supports: <b>, <i>, <u>, <s>, <code>, <pre>, <a>, <blockquote>.
 * This handles the mismatch between what LLMs produce and what Telegram renders.
 */

function escapeHtml(text: string): string {
    return text.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
}

/**
 * Convert standard Markdown to Telegram HTML.
 *
 * Handles: bold (**), italic (* or _), headers (#), bullets (- or *),
 * code blocks (```), inline code (`), links ([]()), strikethrough (~~),
 * and blockquotes (>). Unrecognised syntax passes through as plain text.
 */
export function formatForTelegram(text: string): string {
    const segments: string[] = []

    function protect(html: string): string {
        const idx = segments.length
        segments.push(html)
        return `\x00S${idx}\x00`
    }

    let result = text

    // 1. Protect code blocks (``` ... ```)
    result = result.replace(/```(?:\w*)\n?([\s\S]*?)```/g, (_, code: string) =>
        protect(`<pre>${escapeHtml(code.trim())}</pre>`)
    )

    // 2. Protect inline code (` ... `)
    result = result.replace(/`([^`\n]+)`/g, (_, code: string) =>
        protect(`<code>${escapeHtml(code)}</code>`)
    )

    // 3. Protect links ([text](url))
    result = result.replace(/\[([^\]]+)\]\(([^)]+)\)/g, (_, label: string, url: string) =>
        protect(`<a href="${url}">${escapeHtml(label)}</a>`)
    )

    // 4. Escape remaining HTML entities
    result = escapeHtml(result)

    // 5. Headers → bold on its own line
    result = result.replace(/^#{1,6}\s+(.+)$/gm, "<b>$1</b>")

    // 6. Bold: **text** or __text__
    result = result.replace(/\*\*(.+?)\*\*/g, "<b>$1</b>")
    result = result.replace(/__(.+?)__/g, "<b>$1</b>")

    // 7. Italic/bold single asterisk: *text*
    //    In Telegram context LLMs use single * for bold, so we treat it as bold.
    result = result.replace(/(?<!\w)\*([^*\n]+)\*(?!\w)/g, "<b>$1</b>")

    // 8. Italic: _text_
    result = result.replace(/(?<!\w)_([^_\n]+)_(?!\w)/g, "<i>$1</i>")

    // 9. Strikethrough: ~~text~~
    result = result.replace(/~~(.+?)~~/g, "<s>$1</s>")

    // 10. Bullet points: leading - or * → •
    result = result.replace(/^[-*]\s+/gm, "• ")

    // 11. Blockquotes: > text → strip the marker
    result = result.replace(/^&gt;\s?/gm, "")

    // 12. Horizontal rules
    result = result.replace(/^-{3,}$/gm, "")

    // 13. Restore protected segments
    result = result.replace(/\x00S(\d+)\x00/g, (_, idx) => segments[parseInt(idx)])

    // 14. Collapse excessive blank lines
    result = result.replace(/\n{3,}/g, "\n\n")

    return result.trim()
}
